server:
    address: 192.168.0.100
    port: 9091
    
eureka:
    instance: 
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        server-url:
            default-zone: http://localhost:8761/eureka/
        
        
logging:
  file:
    name: E:/SPRING-BOOT TUTORIAL/Logger/apigateway.log
  level:
    com:
      apigateway: DEBUG
    root: INFO

spring:
    application:
        name: ApiGateway
    
    main:
        web-application-type: reactive
    
        
management:
  endpoints:
    web:
      exposure:
        include: "*" 
      base-path: /v1/apigateway   
  endpoint:
      health:
        show-details: ALWAYS        
        

